[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
    -DBOARD_HAS_PSRAM
lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S#2.0.3
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
